### ISSUE TITLE
Bicycle route not rendered on top of highways

### ISSUE THREAD

**Issue by Phyks** [Phyks/cyclosm-cartocss-style#1]
See 

![capture d ecran 2019-01-23 a 17 41 47](https://user-images.githubusercontent.com/3856586/51622116-3a667900-1f36-11e9-8a5f-c2c79ccf484c.png)

at #18/48.84086/2.38092.

**Comment by Florimondable** [comment]
It's still present see: 
https://tiles.phyks.me/#18/48.85622/2.35877 
or here https://tiles.phyks.me/#18/48.85288/2.28108
the side of the cycleway is under the other highway :(

**Comment by Phyks** [comment]
Hmm, the cycle way might not be rendered (hidden by the other highway) but the route (relation of `type=route`, translucid blue overlay) is always rendered, isn't it?

The cycle way being hidden is another bug, I created https://github.com/Phyks/cyclosm-cartocss-style/issues/29.
